from enum import IntEnum

class MessageType(IntEnum):
    SEND_IMG_FROM_EXT_TO_PY_SERVER = 1,
    SEND_IMG_FROM_PY_SERVER_TO_IMG_SEGMENTATION= 2,
    RETURN_IMG_CUTOUT_FROM_IMG_SEGMENTATION_TO_PY_SERVER = 3,
    SEND_IMG_CUT_OUT_FROM_PY_SERVER_TO_IMG_CLASSIFICATION = 4,
    RETURN_IDENTIFIED_OBJ_NAME_FROM_IMG_CLASSIFICATION_TO_PY_SERVER = 5,
    SEND_IMG_CUTOUT_AND_CATEGORY_PRODUCTS_FROM_PY_SERVER_TO_IMG_COMPARER = 6,
    RETURN_PRODUCT_LIST_FROM_IMG_COMPARER_TO_PY_SERVER = 7,
    RETURN_SEARCH_RESULTS_FROM_PY_SERVER_TO_EXT = 8,
    HEADER = 9,
    END_COMM = 10,
    INIT_COMM = 11,
    ACCEPT_COMM = 12