@startuml

title **Search System Sequence Diagram**

actor user as usr
participant "Chrome extension" as ext
control "Python Server" as psv
database "Product database" as db
participant "Image Segmentation NN (Python)" as sgm
participant "Image Classification NN (Python)" as obj
participant "Image Comparer (C#)" as img

usr -> ext: Submit image
activate usr
activate ext
ext -> psv: Send image
activate psv
psv -> sgm: Send image
activate sgm
sgm --> psv: Return image cutout
deactivate sgm
psv -> obj: Send image cutout
activate obj

obj --> psv: Return identified object name
deactivate obj

alt#Gold #LightBlue Simple case
    psv --> ext: Return object name

    ext --> usr: Return URL link to bol.com

else #Pink Complex case
    psv -> db: Send object name

    activate db
    db --> psv: Return catagory products
    deactivate db

    psv -> img: Send image cutout + catagory products
    activate img
    
    img --> psv: Return product list
    deactivate img

    psv --> ext: Return search results
    deactivate psv

    ext --> usr: Return search results
    deactivate ext
    deactivate usr

    legend
     NN = Neural Network
endlegend
end
@enduml