@startuml activity diagram downloaden grafisch product
start
->//Customer has a microphone and wants to buy at bol.com//;
    :Go to bol.com;
    :Select microphone icon next to search bar;
    :Mention keyword for item;
    :View catalog on bol.com;
stop
@enduml